set MATLAB=C:\Program Files\MATLAB\R2017a
"%DSPACE_ROOT%\Exe\dsmake.exe" -f Racing_2019.mk  ISPROTECTINGMODEL=NOTPROTECTING EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 MAT_FILE=0
